exports.EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPE_ERROR: 2,
    DATABASE_ERROR: 3,
    PRODUCT_NOT_FOUND: 4,
    INVALID_FORMAT: 5,
    CART_NOT_FOUND: 6,
    USER_NOT_FOUND: 7,
    INVALID_TOKEN: 8,
    INVALID_PERMISSIONS: 9,
    INVALID_DATA: 10,
    INVALID_ID: 11,
    INVALID_PASSWORD: 12,
    INVALID_EMAIL: 12,
    INVALID_CREDENTIALS: 13
}